config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root to: "lists#index"
  resources :lists, except: [:edit, :update] do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id, message: "is already in the list" }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :lists, through: :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: :destroy
  before_action :set_list, only: [:new, :create]

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  def set_list
    @list = List.find(params[:list_id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :destroy]

  def index
    @lists = List.all
  end

  def show
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @list.destroy
    raise
    redirect_to root_path, status: :see_other
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<h1>New Bookmark Connected</h1>

<br>
<h3>Add a movie to your NAME list</h3>
<br>

<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment, placeholder: "Enter a comment about the movie" %>
  <%= f.association :movie, prompt: "Select a movie", input_html: {data: {controller: "tom-select"}} %>
  <%= f.submit%>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<h1>List Connected</h1>

<h2>Save any kind of movies</h2>

  <h3>My Lists</h3>
  <%= link_to "Create a movie list", new_list_path%>

<ul>
  <% @lists.each do |list| %>
   <li><%= link_to(list.name, list_path(list) ) %></li>
  <% end %>
</ul>

app/views/lists/new.html.erb
<h1>New List Connected</h1>


<%= simple_form_for @list do |f| %>
  <%= f.input :name %>
  <%= f.button :submit %>
<% end %>

app/views/lists/show.html.erb
<h1>Show List Connected</h1>

<%= link_to("Back", root_path)%>

  <h1><%= @list.name %></h1>

<ul>
  <li>Add movie here
</ul>

<%= link_to("Add Bookmark", new_list_bookmark_path(@list))%>
<br>
<br>
<h2>Bookmarks here</h2>


<ul>

  <% @list.bookmarks.each do |bookmark| %>
    <li>
      <strong><%= bookmark.movie.title %></strong><br>
      <em><%= bookmark.comment %></em>
    </li>
  <% end %>
</ul>

app/views/movies/index.html.erb
<h1>Index Connected</h1>


<ul>
  <% @movies.each.with_index do |movie, index|%>
   <li> <%=index + 1 %> <%=link_to(movie.title, list_movie_path(@list, movie))%> </li>
  <%end%>
</ul>

<%= link_to("Add Movie", "#")%>

app/views/movies/new.html.erb
<h1>New Connected</h1>

<%= simple_form_for @movie do |f| %>
  <%= f.input :title %>
  <%= f.input :overview %>
  <%= f.input :poster_url %>
  <%= f.input :rating %>
  <%= f.button :submit %>
<% end %>

app/views/movies/show.html.erb
<h1>Show Connected</h1>

<ul>
  <li><%="Movie Title: #{@movie.title}"%></li>
  <li><%="Overview: #{@movie.overview}"%></li>
  <li><%="URL: #{@movie.poster_url}"%></li>
  <li><%="Rating: #{@movie.rating}"%></li>
</ul>

<%= link_to("Add movie to list", edit_list_path )%>